### ISSUE TITLE
how to move the area covered by multiple robots

### ISSUE THREAD

**Issue by catdeo** [lucascoelhof/voronoi_hsi#1]
Wow, after reading your project, I feel that you are a very powerful engineer. I am a college student from China. I have just touched the ros and multi-robot fields. It is convenient to consult if you want the area covered by multiple robots to move in a certain direction. How to modify the code?

**Comment by lucascoelhof** [comment]
Oh, really sorry for the super late response.
So, this is an implementation of my master's thesis, available here: https://github.com/lucascoelhof/dissertation
I have no intention to progress this implementation, but you can move the robots to a certain position if you publish on topic "/voronoi/gaussian_info". It will create a density function that will attract the robots to a certain position, and if you keep republishing on this topic, you can make the robots move.
On this [this video](https://www.youtube.com/watch?v=tMZiT0ObciI) please watch at 40s that I created a gaussian density functions and the robots were attracted by it.
